# -*- coding: utf-8 -*-
"""Practica2PROGRA2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AdkJqWv-3wyEWbO5ai9kHYm_6SsAhcfg
"""

#Hecho por Moises Ramses Aguilar Ayma
class MiEntero:
    def __init__(self, valor: int=7):
      self.__valor = valor
    def getVD(self):
      return self.__valor
    def getesPar(self):
      return self.__valor % 2 == 0
    def getesImpar(self):
      return self.__valor % 2 != 0
    def getesPrimo(self):
      n = self.__valor
      if n <= 1:
        return False
      if n <= 3:
        return True
      if n % 2 == 0 or n % 3 == 0:
        return False
      i = 5
      while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
          return False
        i += 6
      return True
    # MÉTODOS ESTÁTICOS
    @staticmethod
    def getValor(valor):
        if isinstance(valor, MiEntero):
            return valor.getVD()
        return valor
    @staticmethod
    def esPar(valor):
        if isinstance(valor, MiEntero):
            valor = valor.getVD()
        return valor % 2 == 0
    @staticmethod
    def esImpar(valor):
        if isinstance(valor, MiEntero):
            valor = valor.getVD()
        return valor % 2 != 0
    @staticmethod
    def esPrimo(valor):
        if isinstance(valor, MiEntero):
            valor = valor.getVD()
        if valor <= 1:
            return False
        if valor <= 3:
            return True
        if valor % 2 == 0 or valor % 3 == 0:
            return False
        i = 5
        while i * i <= valor:
            if valor % i == 0 or valor % (i + 2) == 0:
                return False
            i += 6
        return True
    def __str__(self):
      return "Numero [{}]". \
      format(self.__valor)
mientero = MiEntero()
print("Mi Entero es:", mientero.getVD())
print(mientero.getesPar())
print(mientero.getesImpar())
print(mientero.getesPrimo())
mientero = MiEntero(10)
print("Mi Entero es:", mientero.getVD())
print(mientero.getesPar())
print(mientero.getesImpar())
print(mientero.getesPrimo())
mientero = MiEntero(83)
print("Mi Entero es:", MiEntero.getValor(mientero))
print(MiEntero.esPar(mientero))
print(MiEntero.esImpar(mientero))
print(MiEntero.esPrimo(mientero))